### ISSUE TITLE
Trailing whitespace causes ConfigBuilder to fail

### ISSUE THREAD

**Issue by bpicode** [TNG/config-builder#29]
Assume you have an entry with trailing whitespace in a properties file which is supposed to be mapped to an integer field. The ConfigBuilder fails with the exception:

com.tngtech.configbuilder.exception.PrimitiveParsingException: unable to parse "42 " to int 
at com.tngtech.configbuilder.annotation.typetransformer.StringOrPrimitiveToPrimitiveTransformer.transform(StringOrPrimitiveToPrimitiveTransformer.java:21)
at com.tngtech.configbuilder.util.FieldValueTransformer.performNecessaryTransformations(FieldValueTransformer.java:82)
at com.tngtech.configbuilder.util.FieldValueTransformer.transformFieldValue(FieldValueTransformer.java:45)
at com.tngtech.configbuilder.util.FieldSetter.setFields(FieldSetter.java:36)
at com.tngtech.configbuilder.ConfigBuilder.build(ConfigBuilder.java:265)

A way around this might be to call String.trim() in StringOrPrimitiveToPrimitiveTransformer.

**Comment by theone1984** [comment]
Matthias just created the code to fix this issue and it is now merged to master. It will be included in the next version of the config-builder.

**Comment by bpicode** [comment]
Thanks guys, any idea when the next release will be out?

**Comment by theone1984** [comment]
I cannot do it ATM, but I'll ask Mathias if we could do a minor release

**Comment by bpicode** [comment]
That would be awesome.

**Comment by janschaefer** [comment]
Version 1.3.1 is published now. You can expect it on maven central in about 2-4 hours

**Comment by bpicode** [comment]
Nice! thanks again!
